### ISSUE TITLE
TCK is "software and/or documentation"

### ISSUE THREAD

**Issue by waynebeaton** [EclipseFdn/EFSP#49]
Avoid prescribing the nature of a TCK. It should be possible, for example, to have a TCK that is entirely documentation. I think that we can get there by changing the definition of TCK from 

> Software and documented requirements that support...

to 

>Software and **/or** documented requirements that support...

**Comment by starksm64** [comment]
You really cannot have a TCK that is purely documentation because there is no way to validate conformance. The current TCK license has a requirement that the results of the TCK are made publicly available to claim conformance. I don't see how you can meaningfully do this if the TCK amounts to a collection of logic statements that cannot be portably tested.

**Comment by waynebeaton** [comment]
Sure you can. I can describe inputs and expected outputs. It's entirely possible to have a verification strategy that is entirely manual.

The primary reason why I've added this is to ensure that we're being inclusive of other groups doing things with technology that is very different from what we're doing with Jakarta EE (e.g., Sparkplug and OpenHW).

Individual working groups can (and already do) make specific requirements of the nature of TCKs for specifications being developed under their purview.
