### ISSUE TITLE
More on Patent Licenses

### ISSUE THREAD

**Issue by waynebeaton** [EclipseFdn/EFSP#51]
**Updated July 28/2021**

We need to capture more about Patent Licenses (potentially both in the specification process itself and in the operations guide).

Specifically:

The working group's **Steering** Committee must <Del>set the</del><ins>select a default</del> Patent License policy for the specification <ins>projects</ins> that fall under the purview of the working group. <del>The policy could be a simple statement that a particular Patent License is the default, or can be a more complex if-then-else sort of policy. </del> Approval is by simple majority.

The working group's **Steering** Committee must approval all exceptions to the Patent License policy. Approval is by simple majority.

The working Group's **Specification** Committee must confirm, prior to initiating a ballot that will result in the establishment of a new specification, that the new specification conforms to the Patent License policy.

/cc @mmilinkov @paulbuck

**Comment by edbratt** [comment]
Would the implication be that existing patent option selection would be used, unless the new project requests an exception? 
I'd be curious why we'd suggest exceptions be approved by simple majority. Shouldn't it be harder to get exceptions approved?

**Comment by waynebeaton** [comment]
My first cut went with this language:

> The _Patent License_ defines how patent grants flow from a Final Specification to an implementer of the Specification. The Eclipse Foundation Intellectual Property Policy defines two choices for Patent License: _Implementation Patent License_ or _Compatible Patent License_.
> 
> The Working Group's _Steering Committee_ must set the Patent License Policy for the Specification Projects that fall under the purview of the Working Group. The policy can be a simple statement that a particular Patent License is the default, or can be a more complex. The Steering Committee must approve the Patent License Policy by simple majority.
> 
> The Working Group's Patent License Policy may be updated from time-to-time by the _Steering Committee_. The Steering Committee must approve changes to the Patent License Policy by simple majority. Changes to the Patent License Policy do not affect the Patent License of existing Specification Projects and Specifications.
> 
> All Specifications produced by a Specification Project must use the same Patent License.
> 
> At the time of creation, a proposal to create a new Specification Project or convert an existing Project into a Specification Project must explicitly state its choice of Patent License.
> 
> The Working Group's _Specification Committee_ must confirm, prior to initiating a ballot that will result in the establishment of a Specification Project, that the selection of Patent License conforms to the Patent License Policy. The Working Group's _Steering Committee_ must approve all exceptions to the Patent License Policy by simple majority.

The [IP Policy](https://www.eclipse.org/org/documents/Eclipse_IP_Policy.pdf) is silent on what approvals are required and by whom, so we need to set them in this policy. Based on recent precedence and related discussion, I believe that the Steering Committee is the right body to make this sort of decision. I am hopeful that we can reach consensus that the decision can be made using the standard procedures of the committee (e.g., provide materials in advance of the meeting, vote at the meeting, and minute the results). I chose simple majority because it is the default, but maybe the right answer is to leave it out and let the individual steering committees decide.

Regarding the assertion that "All Specifications produced by a Specification Project must use the same Patent License"...

The Definitions section states this:

> “Patent License” means an Implementation Patent License or a Compatible Patent License, as selected by each Specification **Project**.

And the definition of "Specification" states this:

> Each **Specification** must stipulate whether it implements an Implementation Patent License or a Compatible Patent License.

The Specification Process section states:

> At the commencement of each Specification **Project**, such Specification Project will: (i) have a specified and documented Scope, and (ii) explicitly select whether they will utilize an Implementation Patent License or a Compatible Patent License.

Taken together, I interpret this to mean that the choice of Patent License is made at the **Specification Project** level and--by extension--all Specifications contained therein _must utilize the same Patent License_. 

Furthermore, while I believe that there is room for a working group to have an arbitrarily complex policy regarding the choice of Patent License, the IP Policy is quite clear that a Specification Project must choose exactly one of the two choices; that is, a Specification Project can only have a selection of Patent License, not an arbitrarily complex policy.

**Comment by mmilinkov** [comment]
> 
> 
> Would the implication be that existing patent option selection would be used, unless the new project requests an exception?
> I'd be curious why we'd suggest exceptions be approved by simple majority. Shouldn't it be harder to get exceptions approved?

Ed, 

Good question. The answer is pretty simple: the EFSP and working group charters do not list patent license approval as a topic that requires super-majority approval, and state that anything specifically not called out for super-majority uses simple majority. If the policy itself can be approved by a simple majority, then exceptions should follow the same pattern. That is consistent with both the process and the charters. HTH

**Comment by edbratt** [comment]
I would like to see the process define a "normal" process that the working group follows as normal operations. I would like to suggest that exceptions require more unanimity.  To date, I had the impression this aspect was a decided element in our working group -- and we'd operated that way. Now, we're finding that this decision must be revisited with every new project. I would prefer that the process explicitly address that a working group set this up -- and that change from the norm be treated as an exception. That's how I had thought this worked and it's only been recent events that have shown me that my thinking is incorrect. So -- since there appears to be interest in updating the process, I would like to ask for this (as opposed to having to decide this each and every time a new project is established). The working group chooses an option -- all new projects will follow this unless an exception is allowed. This can define that exception. I believe that continuity is important and Specification users shouldn't have to read the fine print on each and every specification project.

**Comment by waynebeaton** [comment]
> I would like to see the process define a "normal" process that the working group follows as normal operations. 

I agree. The question, though, is how prescriptive we need to be in the foundational process.  Is it enough to say that the Steering Committee must decide using their standard practices for deciding such things, or do we need to be more specific than that?

> I would like to suggest that exceptions require more unanimity. 

Consistency across working groups is actually easier for me, but I want to take care that we do not impose very specific requirements on working groups without having very specific reasons. Is the desire to require more unanimity specific to the Jakarta EE working group, or does this make sense in general. By leaving it as a matter of practice for the Steering Committee, we can let individual working groups decide how they prefer to do it.

> To date, I had the impression this aspect was a decided element in our working group -- and we'd operated that way. 

I do not recall any discussion in the working group that resolved this decision. I can't find anything in the minutes for any committee.

> Now, we're finding that this decision must be revisited with every new project. 

That's not what I've stated above. The policy is established by the Steering Committee. The Specification Committee needs to ensure that the choice of Patent License matches the policy and _only_ exceptions to that policy require intervention from the Steering Committee.

> I would prefer that the process explicitly address that a working group set this up -- and that change from the norm be treated as an exception. 

Our recent updates to the working group process, which have been delivered to the board of directors for their review, make establishing the Patent License a requirement for a working group to exit incubation.

> That's how I had thought this worked and it's only been recent events that have shown me that my thinking is incorrect. So -- since there appears to be interest in updating the process, I would like to ask for this (as opposed to having to decide this each and every time a new project is established). The working group chooses an option -- all new projects will follow this unless an exception is allowed. This can define that exception. 

That's what I intend with these additions. Clearly I have to make this more obvious. I'll take another run at it.

> I believe that continuity is important and Specification users shouldn't have to read the fine print on each and every specification project.

**Comment by edbratt** [comment]
The fact this is a question for the Jakarta EE working group only makes the point that this needs to be clarified and I appreciate you and the Foundation are working to do that. 

For Jakarta EE, the choice appears to have been implicitly decided that all projects in that working group use the Compatible Product Patent option. I don't disagree this decision doesn't appear any of the record yet, that is what all the projects, until recently, have come to exhibit. 

Speaking for Oracle, we were comfortable with that because that was most similar to what had been used in the prior life of Java EE. While the decision may not be recorded it is the defacto choice the group had been operating under. Explicit resolution or not.. This working group is now being confronted with (re) establishing this choice, after having worked under it for a few years now. Both legacy and new projects having been created under this choice, without resolutions, nor comment for that matter. Prior to the most recent revision of the IP policy, it wasn't all that clear (at least to me) that this was a choice to be made, project by project. 

All I am suggesting is -- I would like to see the working group establish it's normative choice -- new projects in that WG ought to conform -- if exceptions are allowed -- they should be treated as exceptions, that exceptional approval bar should indicate that the exception is warranted and has deep agreement by the members (in my opinion). If that involves multiple documents and processes be revised, I guess I'm suggesting that.

As is currently being written -- this appears to be headed toward something suggesting each project within a working working may choose this, purely on it's own merits. I would prefer stronger working group conformance on this point.

Regardless, whatever additional guidance is provided, will certainly be an improvement.

**Comment by starksm64** [comment]
The first time there was a clear statement of any patent license choice was stated was when MicroProfile WG was finalizing. The Jakarta WG never made a vote on this topic. That needs to happen.

**Comment by edbratt** [comment]
Could you clarify -- What is the controlling document that states that a working group must select a default? Why pick one over the other? Couldn't this just be a required element in the Creation review and then the Spec. committee members simply consider this as part of the creation ballot? (Honestly, I thought it worked that was prior than us going down this thread)

**Comment by waynebeaton** [comment]
> Could you clarify -- What is the controlling document that states that a working group must select a default? 

The Working Group Process [states](https://www.eclipse.org/org/workinggroups/process.php#wg-specifications) that, "[t]he Steering Committee must further vote to adopt a default Patent License (either Compatible Patent License or Implementation Patent License) as defined by the Eclipse Foundation Intellectual Property Policy."

> Why pick one over the other? 

I agree that we should provide whatever help we can to make the decision. However, that help doesn't fit in the process document. 

> Couldn't this just be a required element in the Creation review and then the Spec. committee members simply consider this as part of the creation ballot?

It is an aspect of a proposal, so it is a required element of the creation review. The choice needs to be locked down before the specification committee ballot is initiated, and cannot change during the ballot (or after a successful ballot). The specification committee ballot can only be initiated if the patent license choice matches the working group's default or the steering committee approves the exception. A specification committee member can consider the patent license choice when casting their vote.

>  (Honestly, I thought it worked that was prior than us going down this thread)

This all worked before, because we'd defaulted to the Compatible Patent License and all of the projects that we pushed through the system used that default. We learned some lessons along the way that ultimately resulted in this discussion.
